# Сообщение при входе (UTF-8). Разрешены плейсхолдеры {player} и {prefix}
# Цветовая схема: &6, &e, &7, &8
# По умолчанию без префикса:
# join-message: "&6&lVansJoin &8>> &6{player} &eзашёл на сервер!"
# С поддержкой {prefix} перед {player}:
# Сообщение при входе игрока с пермишеном vansjoin.alert
join-message: "&6&lVansJoin &8>> {prefix}&6{player} &eзашёл на сервер!"


